image: golang:1.21.5

variables:
  OS: 
    value: "linux"
    description: "Pick OS"
    options: 
      - "linux"
      - "darwin"
      - "windows"
      - "all"
  ARCH: 
    value: "amd64"
    description: "Pick ARCH"
    options:
      - "amd64"
      - "arm"
      - "arm64"

stages:
  - test
  - build
  - build-image
  - push-image

test:
  stage: test
  script:
    - echo "make test"
    - make test

build:
  stage: build
  script:
    - echo "Build for arch $ARCH and platform $OS"
    - make build TARGETOS=$OS TARGETARCH=$ARCH

build-image:
  stage: build-image
  image: oleksandran/docker-ci:24.0.7
  script:
    - echo "Build image for arch $ARCH and platform $OS"
    - make image TARGETOS=$OS TARGETARCH=$ARCH REGISTRY=oleksandran

push-image:
  stage: push-image
  image: oleksandran/docker-ci:24.0.7
  script:
    - echo "Push image for arch $ARCH and platform $OS"
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - make push TARGETOS=$OS TARGETARCH=$ARCH REGISTRY=oleksandran
