
default:
  image: oleksandran/docker-ci:24.0.7
  services:
    - docker:24.0.7-dind

variables:
  OS: 
    value: "linux"
    description: "Pick OS"
    options: 
      - "linux"
      - "darwin"
      - "windows"
  ARCH: 
    value: "amd64"
    description: "Pick ARCH"
    options:
      - "amd64"
      - "arm"
      - "arm64"

stages:
  - test
  - build

test:
  image: golang:1.21.5
  stage: test
  script:
    - echo "make test"
    - make test
    - echo "Build for arch $ARCH and platform $OS"
    - make build TARGETOS=$OS TARGETARCH=$ARCH

build:
  stage: build
  script:
    - echo "Build image for arch $ARCH and platform $OS"
    - make image TARGETOS=$OS TARGETARCH=$ARCH REGISTRY=$CI_REGISTRY/$CI_PROJECT_PATH
    - echo "Push image for arch $ARCH and platform $OS"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - make push TARGETOS=$OS TARGETARCH=$ARCH REGISTRY=$CI_REGISTRY/$CI_PROJECT_PATH
