{{- if .Values.secret.token }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.secret.name }}
  labels:
    app: {{ .Chart.Name }}
type: Opaque
data:
  {{ .Values.secret.tokenKey }}: {{ .Values.secret.token | b64enc }}
{{ end }}